#
# JavaBean Tester (https://github.com/hazendaz/javabean-tester)
#
# Copyright 2012-2020 Hazendaz.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of The Apache Software License,
# Version 2.0 which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0.txt
#
# Contributors:
#     CodeBox (Rob Dawson).
#     Hazendaz (Jeremy Landis).
#

version: 2
updates:
# Maintain dependencies for Maven dependencies
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: jakarta.annotation:jakarta.annotation-api
      versions:
      - ">= 2.0.0"
    - dependency-name: jakarta.xml.bind:jakarta.xml.bind-api
      versions:
      - ">= 2.0.0"
    - dependency-name: org.hibernate.validator:hibernate-validator-annotation-processor
      versions:
      - ">= 7.0.0.Final"
    - dependency-name: net.revelc.code.formatter:formatter-maven-plugin
      versions:
      - ">= 2.17.0"
    - dependency-name: org.eclipse.jgit:org.eclipse.jgit
      versions:
      - ">= 6.0.0.202111291000-r"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
