name: Coverity

on:
  push:
    branches:
      - coverity_scan

permissions: read-all

jobs:
  build:
    if: github.repository_owner == 'hazendaz'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: maven
          java-version: 21
          distribution: zulu
      - name: Analyze with Coverity
        run: |
          wget -q https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=hazendaz%2Fjavabean-tester" -O coverity_tool.tgz
          tar -xf coverity_tool.tgz
          ./cov-analysis-linux64-*/bin/cov-build --dir cov-int ./mvnw -B -V -DskipTests=true verify --no-transfer-progress -Dlicense.skip=true
          tar czvf javabean-tester.tgz cov-int
          curl --form token=$COVERITY_TOKEN \
            --form email=$EMAIL \
            --form file=@javabean-tester.tgz \
            --form version="javabean-tester/coverity_scan" \
            --form description="Javabean Tester Coverity Scan" \
            https://scan.coverity.com/builds?project=hazendaz%2Fjavabean-tester
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
